In [2]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

2022-07-06 14:14:30.217004: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-06 14:14:30.217028: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [3]:
import pandas as pd

df = pd.read_csv("annotationsfinal.csv")
df.head(5)

611857364396965889  \
0  614484565059596288   
1  614746522043973632   
2  614877582664835073   
3  611932373039644672   
4  611570404268883969   

  @aandraous @britishmuseum @AndrewsAntonio Merci pour le partage! @openwinemap  \
0  Dorian Gray with Rainbow Scarf #LoveWins (from...                              
1  @SelectShowcase @Tate_StIves ... Replace with ...                              
2  @Sofabsports thank you for following me back. ...                              
3  @britishmuseum @TudorHistory What a beautiful ...                              
4  @NationalGallery @ThePoldarkian I have always ...                              

  nocode  
0  happy  
1  happy  
2  happy  
3  happy  
4  happy

In [4]:
df.columns = ['random', 'Tweet', 'Sentiment']

In [5]:
df.groupby('Sentiment').describe()

random                                            \
                    count          mean           std           min   
Sentiment                                                             
angry                57.0  6.119109e+17  1.410195e+15  6.104118e+17   
disgust               6.0  6.130681e+17  1.715073e+15  6.107624e+17   
disgust|angry         7.0  6.124351e+17  1.593844e+15  6.107596e+17   
happy              1137.0  6.130342e+17  3.132433e+15  5.210143e+17   
happy|sad             9.0  6.136165e+17  1.567929e+15  6.116190e+17   
happy|surprise       11.0  6.130532e+17  1.567604e+15  6.105684e+17   
nocode             1571.0  6.127426e+17  6.360210e+15  3.871909e+17   
not-relevant        214.0  6.127273e+17  1.424607e+15  6.083137e+17   
sad                  32.0  6.131118e+17  1.429148e+15  6.104965e+17   
sad|angry             2.0  6.143755e+17  1.000598e+15  6.136680e+17   
sad|disgust           2.0  6.125822e+17  3.043721e+15  6.104299e+17   
sad|disgust|angry     1.0  6.129109e+17           NaN  6.129109e+17   
surprise             35.0  6.131260e+17  1.821907e+15  6.085875e+17   

                                                                           
                            25%           50%           75%           max  
Sentiment                                                                  
angry              6.107477e+17  6.114579e+17  6.133064e+17  6.144741e+17  
disgust            6.117703e+17  6.137034e+17  6.140144e+17  6.149955e+17  
disgust|angry      6.111874e+17  6.123081e+17  6.131752e+17  6.152529e+17  
happy              6.118554e+17  6.132677e+17  6.144167e+17  6.155952e+17  
happy|sad          6.121973e+17  6.129931e+17  6.150997e+17  6.154772e+17  
happy|surprise     6.120040e+17  6.126685e+17  6.144418e+17  6.152539e+17  
nocode             6.115891e+17  6.129786e+17  6.141586e+17  6.155956e+17  
not-relevant       6.116094e+17  6.129711e+17  6.137050e+17  6.155779e+17  
sad                6.118744e+17  6.130778e+17  6.144717e+17  6.151083e+17  
sad|angry          6.140217e+17  6.143755e+17  6.147293e+17  6.150830e+17  
sad|disgust        6.115060e+17  6.125822e+17  6.136583e+17  6.147344e+17  
sad|disgust|angry  6.129109e+17  6.129109e+17  6.129109e+17  6.129109e+17  
surprise           6.115374e+17  6.133116e+17  6.146652e+17  6.155346e+17

In [6]:
df=df.drop(['random'], axis=1)

In [7]:
df=df[df.Sentiment!='nocode']

In [8]:
df.head()

Tweet Sentiment
0  Dorian Gray with Rainbow Scarf #LoveWins (from...     happy
1  @SelectShowcase @Tate_StIves ... Replace with ...     happy
2  @Sofabsports thank you for following me back. ...     happy
3  @britishmuseum @TudorHistory What a beautiful ...     happy
4  @NationalGallery @ThePoldarkian I have always ...     happy

In [9]:
#Down Sampling

non_happy_df=df[df["Sentiment"] != "happy"]
happy_df=df[df["Sentiment"] == "happy"].iloc[:non_happy_df.shape[0]]

In [10]:
df = pd.concat([happy_df, non_happy_df])

In [11]:
df.head()

Tweet Sentiment
0  Dorian Gray with Rainbow Scarf #LoveWins (from...     happy
1  @SelectShowcase @Tate_StIves ... Replace with ...     happy
2  @Sofabsports thank you for following me back. ...     happy
3  @britishmuseum @TudorHistory What a beautiful ...     happy
4  @NationalGallery @ThePoldarkian I have always ...     happy

In [12]:
df.shape

(752, 2)

In [13]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [14]:
df['target']=encoder.fit_transform(df['Sentiment'])

In [15]:
df.head()

Tweet Sentiment  target
0  Dorian Gray with Rainbow Scarf #LoveWins (from...     happy       3
1  @SelectShowcase @Tate_StIves ... Replace with ...     happy       3
2  @Sofabsports thank you for following me back. ...     happy       3
3  @britishmuseum @TudorHistory What a beautiful ...     happy       3
4  @NationalGallery @ThePoldarkian I have always ...     happy       3

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Tweet'],df['target'])

In [17]:
df['Tweet']

0       Dorian Gray with Rainbow Scarf #LoveWins (from...
1       @SelectShowcase @Tate_StIves ... Replace with ...
2       @Sofabsports thank you for following me back. ...
3       @britishmuseum @TudorHistory What a beautiful ...
4       @NationalGallery @ThePoldarkian I have always ...
                              ...                        
3020    @britishmuseum 2000 coins per day...they didn'...
3036    From 12pm on @BBCCambs we preview #CastleHillO...
3043    @BullDeborah @britishmuseum read Jo Nye's book...
3077    @_TheWhitechapel @Campaignforwool @SlowTextile...
3082    @NationalGallery The 2nd GENOCIDE against #Bia...
Name: Tweet, Length: 752, dtype: object

In [18]:
X_train[:10]

395     @MarcusRomer @kettlesyard @andrewnairne The tr...
1019    BAME applicants esp welcome for 1 year cultura...
731     One of the most beautiful Places in London: @N...
925     @NationalGallery This is one of my favourite p...
551     This looks great, so hard to decide which day ...
246     #Cambridge will not be the same for my next vi...
494     https://t.co/KIfbjFNcZV we're hiring a new Dev...
241     @_TheRowanTree_ Thank you. Have a lovely weeke...
476     Fantastic closing exhibition @kettlesyard prov...
543     @tateliverpool Great stuff! I'll be there ASAP...
Name: Tweet, dtype: object

In [19]:
y_train[:10]

395     6
1019    6
731     3
925     3
551     3
246     3
494     6
241     3
476     3
543     3
Name: target, dtype: int64

In [20]:
X_train.head(4)

395     @MarcusRomer @kettlesyard @andrewnairne The tr...
1019    BAME applicants esp welcome for 1 year cultura...
731     One of the most beautiful Places in London: @N...
925     @NationalGallery This is one of my favourite p...
Name: Tweet, dtype: object

In [21]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

2022-07-06 14:14:32.501834: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 14:14:32.502090: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-06 14:14:32.502148: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-07-06 14:14:32.502191: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-07-06 14:14:32.502237: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [22]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up",
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.84351707, -0.51327276, -0.8884572 , ..., -0.7474888 ,
        -0.7531474 ,  0.91964495],
       [-0.8720837 , -0.5054399 , -0.9444668 , ..., -0.8584752 ,
        -0.71745366,  0.8808299 ]], dtype=float32)>

In [23]:
y_train=pd.get_dummies(y_train)

In [24]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(12, activation='softmax', name="output")(l)


model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [25]:
l.shape

TensorShape([None, 12])

In [26]:
text_input.shape

TensorShape([None])

In [27]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer (KerasLayer)       {'input_word_ids':   0           ['text[0][0]']                   
                                (None, 128),                                                      
                                 'input_type_ids':                                                
                                (None, 128),                                                      
                                 'input_mask': (Non                                               
                                e, 128)}                                                      

In [28]:
outputs['pooled_output'].shape

TensorShape([None, 768])

In [29]:
len(X_train)

564

In [30]:
METRICS = [
      tf.keras.metrics.CategoricalCrossentropy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=METRICS)

In [31]:
model.fit(X_train, y_train.values, epochs=10)

Epoch 1/10
18/18 [==============================] - 52s 3s/step - loss: 1.8484 - accuracy: 1.8484 - precision: 0.4583 - recall: 0.2926
Epoch 2/10
18/18 [==============================] - 48s 3s/step - loss: 1.4683 - accuracy: 1.4683 - precision: 0.4654 - recall: 0.2145
Epoch 3/10
18/18 [==============================] - 48s 3s/step - loss: 1.4463 - accuracy: 1.4463 - precision: 0.5113 - recall: 0.3209
Epoch 4/10
18/18 [==============================] - 48s 3s/step - loss: 1.4073 - accuracy: 1.4073 - precision: 0.5470 - recall: 0.3404
Epoch 5/10
18/18 [==============================] - 50s 3s/step - loss: 1.3720 - accuracy: 1.3720 - precision: 0.5607 - recall: 0.2784
Epoch 6/10
18/18 [==============================] - 51s 3s/step - loss: 1.3952 - accuracy: 1.3952 - precision: 0.5526 - recall: 0.3262
Epoch 7/10
18/18 [==============================] - 50s 3s/step - loss: 1.3560 - accuracy: 1.3560 - precision: 0.5922 - recall: 0.3245
Epoch 8/10
18/18 [==============================] - 50s

In [36]:
#y_test=pd.get_dummies(y_test)

In [ ]:
X_test

In [38]:
model.evaluate(X_train, y_train)

18/18 [==============================] - 49s 3s/step - loss: 1.2412 - accuracy: 1.2412 - precision: 0.7609 - recall: 0.3723


[1.2412008047103882, 1.2412008047103882, 0.760869562625885, 0.3723404109477997]

In [33]:
y_train.shape

(564, 12)

In [40]:
import pickle
pickle.dump(encoder, open('vectorizer.pkl', 'wb'))

1/1 [==============================] - 1s 1s/step


array([[0.07234751, 0.01338999, 0.02330925, 0.49142125, 0.01750292,
        0.02490195, 0.28367624, 0.02092175, 0.00424872, 0.00550982,
        0.00346939, 0.03930122],
       [0.06440988, 0.00814942, 0.0116381 , 0.5242965 , 0.01188821,
        0.01455515, 0.29586887, 0.02496774, 0.00294843, 0.00293761,
        0.00209301, 0.03624712],
       [0.06977595, 0.00944616, 0.01868216, 0.46128434, 0.01261424,
        0.01611044, 0.34744197, 0.02273434, 0.0029377 , 0.00258092,
        0.00220985, 0.0341819 ],
       [0.04181352, 0.00882281, 0.01265987, 0.6359902 , 0.01438443,
        0.02411605, 0.16625857, 0.03051194, 0.00331904, 0.00307084,
        0.00156977, 0.05748285],
       [0.05666604, 0.00733487, 0.01064028, 0.6282611 , 0.01212199,
        0.02181256, 0.17469585, 0.03968202, 0.00335515, 0.0020909 ,
        0.00135439, 0.04198488]], dtype=float32)

In [41]:
pickle.dump(model, open('model.pkl', 'wb'))

INFO:tensorflow:Assets written to: ram://16326b54-a299-4f0f-88af-bcb37c069aaf/assets


INFO:tensorflow:Assets written to: ram://16326b54-a299-4f0f-88af-bcb37c069aaf/assets


In [57]:
result2 = model.predict(["Fantastic @johnmcdonnellMP standing up for workers @NationalGallery #noprivatisation while @edvaizey sits on fence! http://t.co/QzBYpUAtQt"])

1/1 [==============================] - 0s 234ms/step


In [58]:
print(result2.argmax())

3


In [61]:
pred1 = model.predict(X_test)

6/6 [==============================] - 18s 3s/step


In [62]:
model.score(pred1, y_test)

AttributeError: 'Functional' object has no attribute 'score'

In [65]:
predictions = [i.argmax() for i in pred1]

In [66]:
predictions

[3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 6,
 6,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 6,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 6,
 6,
 3,
 3,
 3,
 6,
 3,
 3,
 3,
 3]

In [1]:
y_test

NameError: name 'y_test' is not defined